# core/backup.py

#!/usr/bin/env python3
"""
Backup module for AIALL vLLM Gateway
------------------------------------
Chức năng:
- Yêu cầu quyền root (Linux)
- Backup thư mục chứa local models (nếu có)
- Sinh cron script daily trong /etc/cron.daily
- Backup incremental theo ngày (backup-YYYY-MM-DD)
- Không ghi đè backup cũ
- Không crash nếu thư mục nguồn không tồn tại
- Windows: bỏ qua
"""

import os
from pathlib import Path


# ============================================================
#  LOGGING
# ============================================================

def log(msg: str) -> None:
    print(f"[BACKUP] {msg}")


# ============================================================
#  ROOT CHECK
# ============================================================

def is_linux_root() -> bool:
    if hasattr(os, "geteuid"):
        return os.geteuid() == 0
    return False


def require_root() -> None:
    if hasattr(os, "geteuid") and not is_linux_root():
        raise SystemExit("Please run as root (sudo).")


# ============================================================
#  PATHS (vLLM)
# ============================================================

# Thư mục chứa model local (nếu bạn dùng local models)
LOCAL_MODEL_DIR = Path("/opt/vllm/models")

# Thư mục backup
BACKUP_DIR = Path("/var/backups/vllm-models")

# Cron script
CRON_FILE = Path("/etc/cron.daily/vllm-backup")


# ============================================================
#  GENERATE BACKUP SCRIPT
# ============================================================

def generate_script() -> str:
    return f"""#!/bin/bash
# Auto-generated by AIALL vLLM Gateway
set -e
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

SRC="{LOCAL_MODEL_DIR}"
DST="{BACKUP_DIR}"

if [ ! -d "$SRC" ]; then
    echo "[BACKUP] No local model directory found: $SRC"
    exit 0
fi

mkdir -p "$DST"

STAMP=$(date +"%Y-%m-%d")
TARGET="$DST/backup-$STAMP"

if [ -d "$TARGET" ]; then
    echo "[BACKUP] Backup for today already exists: $TARGET"
    exit 0
fi

cp -a "$SRC" "$TARGET"

echo "[BACKUP] Backup completed: $TARGET"
"""


def create_backup_script() -> None:
    CRON_FILE.parent.mkdir(parents=True, exist_ok=True)
    CRON_FILE.write_text(generate_script())
    CRON_FILE.chmod(0o700)
    log(f"Cron script installed: {CRON_FILE}")


# ============================================================
#  SETUP BACKUP SYSTEM
# ============================================================

def setup_backup() -> None:
    if not is_linux_root():
        log("Non-root or non-Linux system — skipping backup setup.")
        return

    log("Setting up vLLM model backup system...")

    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    create_backup_script()

    log("Backup system ready.")


if __name__ == "__main__":
    setup_backup()


